title: Mikael Ribeiro Jørgensen # your name (or website title) here
logo: "/images/billede.jfif?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
24-year-old Data Science master’s degree student who is interested in automation, agile work, Machine Learning, and data analysis. I’m always ready for new challenges, and I take great pleasure in finding solutions to problems.

<br><br>
<a href="https://linkedin.com/in/mikael-ribeiro-j%C3%B8rgensen-5aba35141">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
